import { test, expect } from '@playwright/test';
const url = '/tests/browser/fixtures/ticket-metrics.html', d = { population: 1, observed: 0, unknown: 1, censored: 0, coverage: 0, p50: null, p90: null, p95: null };
const result = { ok: true, enabled: true, definitionVersion: 0, authorizedTickets: 1, window: { from: '2026-01-01T00:00:00Z', to: '2026-01-10T00:00:00Z', asOf: '2026-01-15T00:00:00Z' }, firstResponse: d, resolution: { ...d, uniqueTickets: 0, openingCohort: { population: 1, censored: 1 } }, age: d, cycleAge: d, wait: d, waiting: 1, reopening: { hours: null, numerator: 0, denominator: 0, immature: 0, unknown: 0, rate: null }, flow: { wip: 0, unknown: 1, throughput: 0, uniqueTickets: 0, cycleTime: d }, quality: { legacy: 1, corrections: 0, unknownNature: 1 }, watermark: 1, eventCount: 1, aggregation: { matched: 0, pending: 1, builtAt: null, lagMs: null } };
test('OFF hides metrics; viewer sees unknown and denominators without mutation controls', async ({ page }) => { await page.route('**/api/**', r => r.fulfill({ json: { ok: true, enabled: false } })); await page.goto(url); await expect(page.getByText('Métricas do atendimento', { exact: true })).toHaveCount(0); await page.unroute('**/api/**'); await page.route('**/api/**', r => r.fulfill({ json: result })); await page.goto(url + '?viewer'); await page.getByText('Métricas do atendimento', { exact: true }).click(); await expect(page.getByText(/Taxa indisponível/)).toBeVisible(); await expect(page.getByRole('button', { name: 'Reconstruir agregados autorizados' })).toHaveCount(0); await expect(page.getByRole('columnheader', { name: 'Sem dado' })).toBeVisible(); });
test('revocation clears all indicators; org change discards state', async ({ page }) => { let denied = false; await page.route('**/api/**', r => r.fulfill(denied ? { status: 403, json: { ok: false, error: { code: 'FORBIDDEN', message: 'Negado' } } } : { json: result })); await page.goto(url); await page.getByText('Métricas do atendimento', { exact: true }).click(); await expect(page.getByText(/1 chamados acessíveis/)).toBeVisible(); denied = true; await page.getByRole('button', { name: 'Consultar métricas' }).click(); await expect(page.getByText(/1 chamados acessíveis/)).toHaveCount(0); await page.getByRole('button', { name: 'Trocar organização' }).click(); await expect(page.getByText(/Watermark autorizado/)).toHaveCount(0); });
test('ambiguous replay retries exact window and mobile keeps table inside scroll container', async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); const bodies: unknown[] = []; await page.route('**/api/**', r => { if (r.request().method() === 'POST') {
    bodies.push(r.request().postDataJSON());
    return r.fulfill(bodies.length === 1 ? { status: 503, json: { ok: false, error: { code: 'SERVICE_UNAVAILABLE', message: 'Indisponível' } } } : { json: { ok: true } });
} return r.fulfill({ json: result }); }); await page.goto(url); await page.getByText('Métricas do atendimento', { exact: true }).click(); await page.getByRole('button', { name: 'Reconstruir agregados autorizados' }).click(); await page.getByRole('button', { name: 'Verificar tentativa anterior' }).click(); expect(bodies).toHaveLength(2); expect(bodies[0]).toEqual(bodies[1]); await expect(page.getByText(/1 chamados acessíveis/)).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
