name = "maono-kepler-v1-local"
compatibility_date = "2026-05-21"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "maono_maps_local"
database_id = "00000000-0000-0000-0000-000000000001"
migrations_dir = "migrations"
