import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluateEvidence,REQUIRED_CASES} from '../scripts/central-chamados/cc17/evidence-gate.mjs';
const sha='a'.repeat(40),url='https://evidence.example.test/run',at='2026-09-29T20:00:00Z';
function report(){return {schemaVersion:1,productSha:sha,servedSha:sha,environment:'production',window:{approved:true,approvedBy:'operator',approvedAt:at,evidence:url},schema:{verified:true,evidence:url},review:{approved:true,reviewer:'reviewer',evidence:url},cleanup:{complete:true,evidence:url},configuration:{restored:true,evidence:url},blockers:[],cases:REQUIRED_CASES.map(id=>({id,status:'PASS',productSha:sha,environment:'production',executor:'QA',executedAt:at,evidence:url})),performance:{budget:{approved:true,approvedBy:'operator',approvedAt:at,evidence:url,records:100,concurrency:2,durationSeconds:60,samples:20,maxErrorRate:0,p95Ms:{metrics:100,exports:200,uploads:300}},observed:{records:100,concurrency:2,durationSeconds:60},results:Object.fromEntries(['metrics','exports','uploads'].map(f=>[f,{p95Ms:10,errorRate:0,samples:20}])),invariantsPreserved:true,evidence:url}};}
test('CC17 empty/local/merge-only evidence remains pending',()=>{for(const value of [{},{productSha:sha}, {...report(),environment:'local'}])assert.equal(evaluateEvidence(value,sha).status,'PENDING');});
test('CC17 fully recorded evidence requests final review without authorizing release',()=>{const r=evaluateEvidence(report(),sha);assert.equal(r.status,'READY_FOR_FINAL_REVIEW');assert.equal(r.releaseAuthorized,false);});
test('CC17 duplicate, missing, failed, local or wrong-SHA cases fail closed',()=>{for(const mutate of [r=>r.cases.pop(),r=>r.cases.push(r.cases[0]),r=>r.cases[0].status='FAIL',r=>r.cases[0].environment='local',r=>r.cases[0].productSha='b'.repeat(40)]){const r=report();mutate(r);assert.equal(evaluateEvidence(r,sha).status,'PENDING');}});
test('CC17 zero budget errors is valid; missing thresholds or over-budget result is not',()=>{for(const mutate of [r=>delete r.performance.budget.maxErrorRate,r=>r.performance.results.metrics.errorRate=0.01,r=>r.performance.results.uploads.p95Ms=301,r=>r.performance.results.exports.samples=0,r=>r.performance.observed.concurrency=1,r=>r.performance.budget.approved=false]){const r=report();mutate(r);assert.equal(evaluateEvidence(r,sha).status,'PENDING');}});
test('CC17 cleanup, schema, review, restoration and blockers independently hold the gate',()=>{for(const mutate of [r=>r.cleanup.complete=false,r=>r.configuration.restored=false,r=>r.schema.verified=false,r=>r.review.approved=false,r=>r.blockers=['unresolved'],r=>delete r.window.approvedBy]){const r=report();mutate(r);assert.equal(evaluateEvidence(r,sha).status,'PENDING');}});
