import test from 'node:test';
import assert from 'node:assert/strict';
import { projectMetricTicket, aggregateMetricFacts, metricWindow } from '../functions/_lib/ticket-metrics-domain.js';
import { validatePolicy } from '../functions/_lib/ticket-sla-clock.js';
const day = n => `2026-09-${String(n).padStart(2, '0')}T00:00:00.000Z`, window = { from: day(1), to: day(20), asOf: day(25) };
const policy = validatePolicy({ name: 'Synthetic', responseMinutes: 60, resolutionMinutes: 480, responders: [2], pauseReasons: [], calendar: { timeZone: 'UTC', from: '2026-09-01', through: '2026-09-30', weekly: Array.from({ length: 7 }, () => [[0, 1440]]), exceptions: {} } });
function source(id = 1) { return { ticket: { id, created_by: 1, created_at: day(1) }, cycles: [{ cycle_number: 1, origin: 'created', opened_at: day(1), closed_at: null }], events: [], waits: [], messages: [], assignments: [{ cycle_number: 1, sequence: 1, policy_version: 1, effective_at: day(1) }], policies: [{ version: 1, policy_json: JSON.stringify(policy) }] }; }
const fact = (s, d = { version: 1, reopen_hours: 48 }) => projectMetricTicket(s, window, d);
test('CT37 observed percentiles, n, coverage and censored openings', () => { const a = source(), b = source(2); a.messages = [{ id: 'm', created_at: day(2), author_user_id: 2, kind: 'response', audience: 'ticket' }]; a.cycles[0].closed_at = day(3); const r = aggregateMetricFacts([fact(a), fact(b)], window); assert.equal(r.firstResponse.observed, 1); assert.equal(r.firstResponse.censored, 1); assert.equal(r.firstResponse.p90, 86400000); assert.equal(r.firstResponse.coverage, .5); assert.equal(r.resolution.openingCohort.censored, 1); assert.equal(r.age.observed, 1); assert.equal(r.age.p90, 24 * 86400000); });
test('CT38 maturity, inside/outside horizon and zero denominator', () => { const a = source(); a.cycles = [{ cycle_number: 1, origin: 'created', opened_at: day(1), closed_at: day(2) }, { cycle_number: 2, origin: 'reopened', opened_at: day(3), closed_at: day(4) }, { cycle_number: 3, origin: 'reopened', opened_at: day(10), closed_at: day(19) }]; let r = fact(a, { version: 1, reopen_hours: 48 }); assert.equal(r.reopening.numerator, 1); assert.equal(r.reopening.denominator, 3); r = projectMetricTicket(a, { ...window, asOf: day(20) }, { version: 1, reopen_hours: 48 }); assert.equal(r.reopening.immature, 1); assert.equal(r.reopening.denominator, 2); assert.equal(aggregateMetricFacts([], window).reopening.rate, null); assert.equal(fact(a, { version: 0, reopen_hours: null }).reopening.denominator, 0); });
test('CT39 identical duplicate IDs dedup, late event reprojects, corrections remain unknown', () => { const a = source(); a.cycles[0].closed_at = day(8); const e = { id: 1, created_at: day(2), command_id: 'c', entity_version: 1, event_type: 'ticket.status.changed', metadata: JSON.stringify({ to: 'in_progress' }) }; a.events = [e]; const one = fact(a); a.events = [e, e]; assert.deepEqual(fact(a), one); a.events.push({ ...e, id: 2, created_at: day(1) }); assert.equal(fact(a).cycleTimes[0], 7 * 86400000); a.events.push({ ...e, id: 3, corrects_event_id: 1 }); assert.equal(fact(a).resolution[0].raw, null); assert.equal(fact(a).quality.correction, true); });
test('CT40 legacy never zero; open waits clipped and overlapping waits unioned', () => { const a = source(); a.cycles[0].origin = 'observed_baseline'; let r = fact(a); assert.equal(r.age, null); assert.equal(r.response, null); assert.equal(r.responseUnknown, true); const b = source(2); b.waits = [{ reason: 'cliente', started_at: day(2), ended_at: day(5) }, { reason: 'cliente', started_at: day(4), ended_at: null }]; r = fact(b); assert.equal(r.wait, 18 * 86400000); assert.equal(r.waitByReason.cliente, r.wait); assert.equal(r.waiting, true); });
test('response rejects requester, internal, bot and absent roster; future events excluded', () => { for (const m of [{ author_user_id: 1, kind: 'response', audience: 'ticket' }, { author_user_id: 2, kind: 'internal', audience: 'internal' }, { author_user_id: 9, kind: 'response', audience: 'ticket' }]) {
    const a = source();
    a.messages = [{ id: 'm', created_at: day(2), ...m }];
    assert.equal(fact(a).response, null);
} const a = source(); a.messages = [{ id: 'm', created_at: day(26), author_user_id: 2, kind: 'response', audience: 'ticket' }]; assert.equal(fact(a).response, null); a.assignments = []; assert.equal(fact(a).responseUnknown, true); });
test('window is half-open; invalid, inverted and future windows fail', () => { assert.throws(() => metricWindow({ from: day(3), to: day(2), asOf: day(4) })); assert.throws(() => metricWindow({ ...window, asOf: '2099-01-01' })); const a = source(); a.cycles[0].closed_at = window.to; assert.equal(fact(a).resolution.length, 0); });
test('legacy without any cycle remains in backlog with unknown age/wait, useful prefixes not counted', () => { const a = source(); a.cycles = []; a.ticket.status = 'open'; const r = aggregateMetricFacts([fact(a)], window); assert.equal(r.age.population, 1); assert.equal(r.age.unknown, 1); assert.equal(r.wait.unknown, 1); const b = source(); b.assignments[0].effective_at = day(2); b.cycles[0].closed_at = day(4); b.messages = [{ id: 'm', created_at: day(3), author_user_id: 2, kind: 'response', audience: 'ticket' }]; assert.equal(fact(b).responseUseful, null); assert.equal(fact(b).resolution[0].useful, null); });
