import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createTicketCommandDb, COMMAND_ACTORS } from './helpers/ticket-command-db.mjs';
import { publishSlaPolicy, assignSlaPolicy, readTicketSla } from '../functions/_lib/ticket-sla.js';
import { onRequest as policiesRoute } from '../functions/api/organizations/[id]/tickets/sla-policies.js';
import { onRequest as slaRoute } from '../functions/api/organizations/[id]/tickets/[ticketId]/sla.js';
const actor = COMMAND_ACTORS.owner;
const read = p => readFileSync(new URL('../' + p, import.meta.url), 'utf8');
async function fixture(t) { const f = await createTicketCommandDb(t); for (const x of ['0027_ticket_selective_access.sql', '0028_ticket_conversations.sql', '0033_ticket_sla_policies.sql'])
    f.sqlite.exec(read('migrations/' + x)); Object.assign(f.env, { MAONO_TICKET_SLA_ENABLED: 'true', MAONO_TICKET_SLA_ORGANIZATION_IDS: '1', MAONO_TICKET_SELECTIVE_ACCESS_ENABLED: 'true', MAONO_TICKET_CONVERSATIONS_ENABLED: 'true' }); return f; }
function body() { const year = new Date().getUTCFullYear(); return { requestId: crypto.randomUUID(), expectedVersion: 0, approved: true, reason: 'Contrato sintético aprovado para teste', policy: { name: 'SLA teste', responseMinutes: 60, resolutionMinutes: 480, responders: [2], pauseReasons: ['cliente'], calendar: { timeZone: 'UTC', from: `${year}-01-01`, through: `${year}-12-31`, weekly: Array.from({ length: 7 }, () => [[0, 1440]]), exceptions: {} } } }; }
function seed(f) { const now = new Date(Date.now() - 3600000).toISOString(); f.sqlite.prepare("INSERT INTO organization_tickets(id,organization_id,code,subject,description,status,priority,category,created_by,created_at,updated_at,current_cycle_number) VALUES(1,1,'SLA','Teste','Teste','open','normal','support',1,?,?,1)").run(now, now); f.sqlite.prepare("INSERT INTO ticket_cycles(organization_id,ticket_id,cycle_number,origin,opened_at,opened_by) VALUES(1,1,1,'created',?,1)").run(now); }
test('immutable policy versions, CAS, idempotency, audit and atomic failure', async (t) => { const f = await fixture(t), b = body(); const p = await publishSlaPolicy(f.env, 1, actor, b); assert.equal(p.version, 1); assert.equal((await publishSlaPolicy(f.env, 1, actor, b)).replayed, true); await assert.rejects(publishSlaPolicy(f.env, 1, actor, { ...b, reason: 'Alterado pela repetição' }), { status: 409 }); await assert.rejects(publishSlaPolicy(f.env, 1, actor, { ...b, requestId: crypto.randomUUID() }), { status: 412 }); assert.throws(() => f.sqlite.exec("UPDATE ticket_sla_policies SET reason='new reason'"), /IMMUTABLE/); f.failNextBatchAt(1); await assert.rejects(publishSlaPolicy(f.env, 1, actor, { ...b, expectedVersion: 1, requestId: crypto.randomUUID() })); assert.equal(f.rows('ticket_sla_policies').length, 1); assert.equal(f.rows('audit_logs').filter(x => x.action === 'ticket.sla.policy.published').length, 1); });
test('explicit assignment starts coverage, repeated read is no-write, no policy is no SLA', async (t) => { const f = await fixture(t); seed(f); assert.equal((await readTicketSla(f.env, 1, 1, actor)).cycles[0].status, 'no_sla'); await publishSlaPolicy(f.env, 1, actor, body()); const b = { requestId: crypto.randomUUID(), expectedVersion: 0, policyVersion: 1, cycle: 1, reason: 'Aplicação explícita da política' }; await assignSlaPolicy(f.env, 1, 1, actor, b); assert.equal((await assignSlaPolicy(f.env, 1, 1, actor, b)).replayed, true); const before = f.rows('audit_logs').length; const r = await readTicketSla(f.env, 1, 1, actor); assert.equal(r.assignmentVersion, 1); assert.equal(r.cycles[0].uncoveredPrefix, true); assert.equal(f.rows('audit_logs').length, before); assert.deepEqual(f.sqlite.prepare('PRAGMA foreign_key_check').all(), []); assert.equal(f.sqlite.prepare('PRAGMA quick_check').get().quick_check, 'ok'); await assert.rejects(assignSlaPolicy(f.env, 1, 1, actor, { ...b, requestId: crypto.randomUUID() }), { status: 412 }); });
test('private ticket, cross-org and allowlist denied; missing flags do not promise SLA', async (t) => { const f = await fixture(t); seed(f); f.sqlite.exec("UPDATE organization_tickets SET visibility='private'"); await assert.rejects(readTicketSla(f.env, 1, 1, COMMAND_ACTORS.viewer), { status: 404 }); await assert.rejects(readTicketSla(f.env, 2, 1, actor), { status: 404 }); f.sqlite.exec("UPDATE organization_tickets SET visibility='organization'"); f.env.MAONO_TICKET_SLA_ENABLED = 'false'; assert.deepEqual(await readTicketSla(f.env, 1, 1, actor), { enabled: false }); f.env.MAONO_TICKET_SLA_ENABLED = 'true'; f.env.MAONO_TICKET_SLA_ORGANIZATION_IDS = '*'; assert.deepEqual(await readTicketSla(f.env, 1, 1, actor), { enabled: false }); });
test('HTTP requires manage, JSON/same-origin; anonymous denied and read has no-store', async (t) => { const f = await fixture(t); seed(f); const url = 'https://local.test/api/organizations/1/tickets/sla-policies'; const post = (cookie, origin = 'https://local.test') => policiesRoute({ env: f.env, params: { id: '1' }, request: new Request(url, { method: 'POST', headers: { cookie, origin, 'Content-Type': 'application/json' }, body: JSON.stringify(body()) }) }); assert.equal((await post(f.sessionCookie(3))).status, 403); assert.equal((await post(f.sessionCookie(1), 'https://evil.test')).status, 403); const r = await slaRoute({ env: f.env, params: { id: '1', ticketId: '1' }, request: new Request(url, { headers: { cookie: f.sessionCookie(1) } }) }); assert.equal(r.status, 200); assert.equal(r.headers.get('Cache-Control'), 'private, no-store'); assert.equal((await post('')).status, 401); });
test('partial schema and unavailable source flags fail closed', async (t) => { const f = await fixture(t); seed(f); f.sqlite.exec('DROP TRIGGER ticket_sla_assignment_no_update'); await assert.rejects(readTicketSla(f.env, 1, 1, actor), { code: 'TICKET_SLA_NOT_READY' }); });
test('CT34 real conversation provenance excludes internal messages and completes only public peer response', async (t) => { const { resolveTicketConversationContext, createTicketMessage } = await import('../functions/_lib/ticket-conversations.js'); const f = await fixture(t); seed(f); await publishSlaPolicy(f.env, 1, actor, body()); await assignSlaPolicy(f.env, 1, 1, actor, { requestId: crypto.randomUUID(), expectedVersion: 0, cycle: 1, policyVersion: 1, reason: 'Contrato aprovado sintético' }); const context = await resolveTicketConversationContext(f.env, 1, 1, COMMAND_ACTORS.peer); const req = () => new Request('https://local.test/messages', { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': 'application/json' } }); await createTicketMessage(f.env, context, { kind: 'internal', body: 'Nota privada' }, req()); assert.equal((await readTicketSla(f.env, 1, 1, actor)).firstResponse, null); await createTicketMessage(f.env, context, { kind: 'response', body: 'Resposta humana pública' }, req()); assert.ok((await readTicketSla(f.env, 1, 1, actor)).firstResponse?.at); });
test('assignment loses a close race without audit or assignment', async (t) => { const f = await fixture(t); seed(f); await publishSlaPolicy(f.env, 1, actor, body()); const b = { requestId: crypto.randomUUID(), expectedVersion: 0, cycle: 1, policyVersion: 1, reason: 'Contrato aprovado sintético' }; f.beforeNextBatch(() => f.sqlite.exec("UPDATE ticket_cycles SET closed_at='2099-01-01T00:00:00.000Z' WHERE ticket_id=1")); await assert.rejects(assignSlaPolicy(f.env, 1, 1, actor, b), { status: 412 }); assert.equal(f.rows('ticket_sla_assignments').length, 0); assert.equal(f.rows('audit_logs').filter(x => x.action === 'ticket.sla.policy.assigned').length, 0); });
