import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createTicketCommandDb, COMMAND_ACTORS } from './helpers/ticket-command-db.mjs';
import { readMetrics, replayMetrics, publishMetricDefinition } from '../functions/_lib/ticket-metrics.js';
import { onRequest } from '../functions/api/organizations/[id]/tickets/metrics.js';
const actor = COMMAND_ACTORS.owner, win = { from: '2026-01-01T00:00:00.000Z', to: '2026-01-10T00:00:00.000Z', asOf: '2026-01-15T00:00:00.000Z' };
const read = p => readFileSync(new URL('../' + p, import.meta.url), 'utf8');
async function fixture(t) { const f = await createTicketCommandDb(t); for (const name of ['0027_ticket_selective_access.sql', '0028_ticket_conversations.sql', '0033_ticket_sla_policies.sql', '0034_ticket_metric_rollups.sql'])
    f.sqlite.exec(read('migrations/' + name)); Object.assign(f.env, { MAONO_TICKET_METRICS_ENABLED: 'true', MAONO_TICKET_METRICS_ORGANIZATION_IDS: '1', MAONO_TICKET_SLA_ENABLED: 'true', MAONO_TICKET_SLA_ORGANIZATION_IDS: '1', MAONO_TICKET_SELECTIVE_ACCESS_ENABLED: 'true', MAONO_TICKET_CONVERSATIONS_ENABLED: 'true' }); return f; }
function seed(f, id = 1, org = 1, visibility = 'organization') { f.sqlite.prepare("INSERT INTO organization_tickets(id,organization_id,subject,description,status,created_by,created_at,updated_at,current_cycle_number,visibility) VALUES(?,?,'metric','test','open',1,'2026-01-01T00:00:00.000Z','2026-01-01T00:00:00.000Z',1,?)").run(id, org, visibility); f.sqlite.prepare("INSERT INTO ticket_cycles(organization_id,ticket_id,cycle_number,origin,opened_at,opened_by) VALUES(?,?,1,'created','2026-01-01T00:00:00.000Z',1)").run(org, id); }
const config = () => ({ approved: true, expectedVersion: 0, reopenHours: 48, reason: 'Parâmetro sintético aprovado', requestId: crypto.randomUUID() });
test('GET no writes, replay reconciles and identical retry adds no checkpoint; delayed event changes partition', async (t) => { const f = await fixture(t); seed(f); const before = f.rows('audit_logs').length; let r = await readMetrics(f.env, 1, actor, win); assert.equal(r.age.observed, 1); assert.equal(f.rows('audit_logs').length, before); r = await replayMetrics(f.env, 1, actor, win); assert.equal(r.replay.changed, 1); assert.equal(r.aggregation.matched, 1); assert.equal((await replayMetrics(f.env, 1, actor, win)).replay.changed, 0); assert.equal(f.rows('ticket_metric_checkpoints').length, 1); f.sqlite.exec("INSERT INTO ticket_events(organization_id,ticket_id,event_type,actor_user_id,metadata,created_at) VALUES(1,1,'late',1,'{}','2026-01-02T00:00:00.000Z')"); assert.equal((await readMetrics(f.env, 1, actor, win)).aggregation.pending, 1); assert.equal((await replayMetrics(f.env, 1, actor, win)).replay.changed, 1); const checkpoints = f.rows('ticket_metric_checkpoints'); assert.equal(checkpoints.length, 2); assert.equal(checkpoints[1].previous_hash, checkpoints[0].source_hash); });
test('ACL before aggregation and replay: private and cross-org excluded, viewer revocation fails closed', async (t) => { const f = await fixture(t); seed(f); seed(f, 2, 1, 'private'); seed(f, 3, 2); const r = await replayMetrics(f.env, 1, actor, win); assert.equal(r.authorizedTickets, 1); assert.equal(f.rows('ticket_metric_rollups').length, 1); f.beforeNextBatch(() => f.sqlite.exec("UPDATE organization_tickets SET visibility='private' WHERE id=1")); assert.equal((await readMetrics(f.env, 1, actor, win)).authorizedTickets, 0); f.sqlite.exec('DELETE FROM organization_users WHERE organization_id=1 AND user_id=1'); await assert.rejects(readMetrics(f.env, 1, actor, win), { status: 403 }); });
test('definition is immutable, approval explicit, CAS and idempotence survive retry', async (t) => { const f = await fixture(t), b = config(); assert.equal((await publishMetricDefinition(f.env, 1, actor, b)).version, 1); assert.equal((await publishMetricDefinition(f.env, 1, actor, b)).replayed, true); await assert.rejects(publishMetricDefinition(f.env, 1, actor, { ...b, reopenHours: 72 }), { status: 409 }); await assert.rejects(publishMetricDefinition(f.env, 1, actor, { ...b, requestId: crypto.randomUUID() }), { status: 412 }); assert.throws(() => f.sqlite.exec('UPDATE ticket_metric_definitions SET reopen_hours=72'), /IMMUTABLE/); await assert.rejects(publishMetricDefinition(f.env, 1, actor, { ...config(), approved: false })); const r = await readMetrics(f.env, 1, actor, { ...win, definitionVersion: 0 }); assert.equal(r.reopening.hours, null); });
test('atomic rollback of rollup/checkpoint and integrity', async (t) => { const f = await fixture(t); seed(f); const batch = f.env.DB.batch.bind(f.env.DB); let batches = 0; f.env.DB.batch = async (statements) => { if (++batches === 2)
    f.failNextBatchAt(1); return batch(statements); }; await assert.rejects(replayMetrics(f.env, 1, actor, win)); assert.equal(f.rows('ticket_metric_rollups').length, 0); assert.equal(f.rows('ticket_metric_checkpoints').length, 0); assert.deepEqual(f.sqlite.prepare('PRAGMA foreign_key_check').all(), []); assert.equal(f.sqlite.prepare('PRAGMA quick_check').get().quick_check, 'ok'); });
test('HTTP authentication, manage permission, origin and no-store', async (t) => { const f = await fixture(t); seed(f); const url = 'https://local.test/api/organizations/1/tickets/metrics?' + new URLSearchParams(win); const req = (id, body, origin = 'https://local.test') => onRequest({ env: f.env, params: { id: '1' }, request: new Request(url, { method: body ? 'POST' : 'GET', headers: { cookie: id ? f.sessionCookie(id) : '', origin, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }) }); assert.equal((await req()).status, 401); assert.equal((await req(3, { action: 'replay', ...win })).status, 403); assert.equal((await req(1, { action: 'replay', ...win }, 'https://evil.test')).status, 403); const r = await req(1); assert.equal(r.status, 200); assert.equal(r.headers.get('Cache-Control'), 'private, no-store'); });
test('flags, partial schema and oversized universes fail closed', async (t) => { const f = await fixture(t); f.env.MAONO_TICKET_METRICS_ORGANIZATION_IDS = '*'; assert.deepEqual(await readMetrics(f.env, 1, actor, win), { enabled: false }); f.env.MAONO_TICKET_METRICS_ORGANIZATION_IDS = '1'; for (let i = 1; i <= 201; i++)
    seed(f, i); await assert.rejects(readMetrics(f.env, 1, actor, win), { code: 'TICKET_METRICS_LIMIT' }); f.sqlite.exec('DROP TRIGGER ticket_metric_checkpoint_no_delete'); await assert.rejects(readMetrics(f.env, 1, actor, win), { code: 'TICKET_METRICS_NOT_READY' }); });
test('public human response uses real conversation provenance; internal note cannot change visible metrics', async (t) => { const { publishSlaPolicy, assignSlaPolicy } = await import('../functions/_lib/ticket-sla.js'); const { resolveTicketConversationContext, createTicketMessage } = await import('../functions/_lib/ticket-conversations.js'); const f = await fixture(t); seed(f); await publishSlaPolicy(f.env, 1, actor, { requestId: crypto.randomUUID(), expectedVersion: 0, approved: true, reason: 'Calendário sintético aprovado', policy: { name: 'Teste', responseMinutes: 60, resolutionMinutes: 480, responders: [2], pauseReasons: [], calendar: { timeZone: 'UTC', from: '2026-01-01', through: '2026-12-31', weekly: Array.from({ length: 7 }, () => [[0, 1440]]), exceptions: {} } } }); await assignSlaPolicy(f.env, 1, 1, actor, { requestId: crypto.randomUUID(), expectedVersion: 0, cycle: 1, policyVersion: 1, reason: 'Teste explícito da política' }); const context = await resolveTicketConversationContext(f.env, 1, 1, COMMAND_ACTORS.peer); const req = () => new Request('https://local.test/messages', { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID(), 'Content-Type': 'application/json' } }); const w = { from: win.from, to: new Date().toISOString(), asOf: new Date().toISOString() }; const before = await readMetrics(f.env, 1, actor, w); await createTicketMessage(f.env, context, { kind: 'internal', body: 'Nota privada' }, req()); const note = await readMetrics(f.env, 1, actor, { ...w, asOf: new Date().toISOString() }); assert.equal(note.eventCount, before.eventCount); assert.equal(note.firstResponse.observed, 0); await createTicketMessage(f.env, context, { kind: 'response', body: 'Resposta humana substantiva' }, req()); const r = await readMetrics(f.env, 1, actor, { ...w, asOf: new Date().toISOString() }); assert.equal(r.firstResponse.observed, 1); assert.equal(r.firstResponse.useful.observed, 0); });
test('ACL revoked after snapshot invalidates response, not merely next request', async (t) => { const f = await fixture(t); seed(f); const batch = f.env.DB.batch.bind(f.env.DB); f.env.DB.batch = async (statements) => { const result = await batch(statements); f.sqlite.exec("UPDATE organization_tickets SET visibility='private' WHERE id=1"); return result; }; await assert.rejects(readMetrics(f.env, 1, actor, win), { code: 'TICKET_METRICS_ACCESS_CHANGED' }); });
test('snapshot excludes tickets created after asOf and rejects drift in definition selection', async t => { const f = await fixture(t); seed(f); seed(f,2); f.sqlite.exec("UPDATE organization_tickets SET created_at='2026-02-01T00:00:00.000Z' WHERE id=2"); const r=await readMetrics(f.env,1,actor,win); assert.equal(r.authorizedTickets,1); await assert.rejects(readMetrics(f.env,1,actor,{...win,definitionVersion:999}),{status:404}); });
