import { useEffect, useState, type FormEvent } from "react";

type User = { id:number; name?:string; email:string; role:string; active?:boolean; projectCount?:number };
type Organization = { id:number; name:string; slug:string; active?:boolean };
type Membership = Organization & { assigned:boolean; accessLevel:string };
type Draft = { name:string; email:string; role:string; active:boolean; password:string };

async function json(response:Response){const data=await response.json();if(!response.ok||data?.ok===false)throw new Error(data?.error?.message||data?.error||"Erro na requisição.");return data}
const headers={Accept:"application/json","Content-Type":"application/json"};

export default function AdminUserManager({users,currentUserId,isSuperAdmin,onRefresh,onMessage}:{users:User[];currentUserId?:number;isSuperAdmin:boolean;onRefresh:()=>Promise<void>;onMessage:(kind:"error"|"success",text:string)=>void}){
  const [selected,setSelected]=useState<User|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [memberships,setMemberships]=useState<Membership[]>([]);const [busy,setBusy]=useState(false);const [creating,setCreating]=useState(false);
  useEffect(()=>{if(!selected){setDraft(null);setMemberships([]);return}setDraft({name:selected.name||"",email:selected.email,role:selected.role,active:selected.active!==false,password:""});if(isSuperAdmin)fetch(`/api/admin/users/${selected.id}/organizations`,{credentials:"include",headers:{Accept:"application/json"}}).then(json).then(data=>setMemberships(data.organizations||[])).catch(error=>onMessage("error",error.message))},[selected,isSuperAdmin]);
  async function save(event:FormEvent){event.preventDefault();if(!selected||!draft)return;setBusy(true);try{await fetch(`/api/admin/users/${selected.id}`,{method:"PATCH",credentials:"include",headers,body:JSON.stringify({...draft,password:draft.password||undefined})}).then(json);onMessage("success","Usuário atualizado. Sessões foram encerradas caso a senha tenha mudado.");setSelected(null);await onRefresh()}catch(error){onMessage("error",error instanceof Error?error.message:"Falha ao atualizar.")}finally{setBusy(false)}}
  async function remove(){if(!selected||!confirm(`Excluir definitivamente ${selected.email}? Esta ação remove sessões e vínculos.`))return;setBusy(true);try{await fetch(`/api/admin/users/${selected.id}`,{method:"DELETE",credentials:"include",headers:{Accept:"application/json"}}).then(json);onMessage("success","Usuário excluído.");setSelected(null);await onRefresh()}catch(error){onMessage("error",error instanceof Error?error.message:"Falha ao excluir.")}finally{setBusy(false)}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);try{await fetch("/api/admin/users",{method:"POST",credentials:"include",headers,body:JSON.stringify({name:form.get("name"),email:form.get("email"),role:form.get("role"),password:form.get("password"),active:true})}).then(json);onMessage("success","Usuário criado com senha inicial protegida.");setCreating(false);await onRefresh()}catch(error){onMessage("error",error instanceof Error?error.message:"Falha ao criar.")}finally{setBusy(false)}}
  async function updateMembership(org:Membership,assigned:boolean,accessLevel=org.accessLevel){if(!selected)return;setBusy(true);try{await fetch(`/api/admin/users/${selected.id}/organizations/${org.id}`,{method:assigned?"PUT":"DELETE",credentials:"include",headers,body:assigned?JSON.stringify({accessLevel}):undefined}).then(json);setMemberships(items=>items.map(item=>item.id===org.id?{...item,assigned,accessLevel}:item));onMessage("success",assigned?"Organização atribuída.":"Organização removida.");await onRefresh()}catch(error){onMessage("error",error instanceof Error?error.message:"Falha no vínculo.")}finally{setBusy(false)}}
  return <section className="admin-user-manager"><header><div><h2>Usuários e Permissões</h2><p>Crie, edite, desative, exclua, altere senhas e atribua organizações.</p></div><button className="mm-btn primary" type="button" onClick={()=>setCreating(true)}>＋ Novo usuário</button></header><div className="admin-users-table"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Projetos</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td>{user.name||"—"}</td><td>{user.email}</td><td>{user.role}</td><td>{user.projectCount||0}</td><td>{user.active===false?"Inativo":"Ativo"}</td><td><button className="mm-btn tiny" type="button" onClick={()=>setSelected(user)}>Editar</button></td></tr>)}</tbody></table></div>
  {(selected&&draft)&&<div className="admin-user-modal" role="dialog" aria-modal="true"><div className="admin-user-dialog"><header><div><span>GESTÃO GLOBAL</span><h3>Editar usuário</h3></div><button onClick={()=>setSelected(null)} aria-label="Fechar">×</button></header><form onSubmit={save}><div className="admin-user-form-grid"><label>Nome<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>E-mail<input type="email" value={draft.email} onChange={e=>setDraft({...draft,email:e.target.value})}/></label><label>Perfil<select value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="client">Cliente/Owner</option><option value="admin">Admin</option></select></label><label>Situação<select value={draft.active?"active":"inactive"} onChange={e=>setDraft({...draft,active:e.target.value==="active"})}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label><label className="wide">Atribuir ou alterar senha<input type="password" minLength={8} autoComplete="new-password" value={draft.password} onChange={e=>setDraft({...draft,password:e.target.value})} placeholder="Deixe vazio para manter a senha atual"/></label></div>{isSuperAdmin&&<section className="admin-memberships"><h4>Organizações atribuídas</h4>{memberships.map(org=><div key={org.id}><label><input type="checkbox" checked={org.assigned} disabled={busy} onChange={e=>void updateMembership(org,e.target.checked)}/><span><strong>{org.name}</strong><small>{org.slug}</small></span></label><select value={org.accessLevel} disabled={!org.assigned||busy} onChange={e=>void updateMembership(org,true,e.target.value)}><option value="viewer">Consulta</option><option value="editor">Colaborador</option><option value="owner">Responsável</option></select></div>)}</section>}<footer><button type="button" className="mm-btn danger" disabled={busy||selected.id===currentUserId} onClick={()=>void remove()}>Excluir usuário</button><span/><button type="button" className="mm-btn" onClick={()=>setSelected(null)}>Cancelar</button><button className="mm-btn primary" disabled={busy}>{busy?"Salvando...":"Salvar"}</button></footer></form></div></div>}
  {creating&&<div className="admin-user-modal" role="dialog" aria-modal="true"><div className="admin-user-dialog compact"><header><h3>Novo usuário</h3><button onClick={()=>setCreating(false)} aria-label="Fechar">×</button></header><form onSubmit={create}><div className="admin-user-form-grid"><label>Nome<input name="name" required/></label><label>E-mail<input name="email" type="email" required/></label><label>Perfil<select name="role"><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="client">Cliente/Owner</option><option value="admin">Admin</option></select></label><label>Senha inicial<input name="password" type="password" minLength={8} autoComplete="new-password" required/></label></div><footer><span/><span/><button type="button" className="mm-btn" onClick={()=>setCreating(false)}>Cancelar</button><button className="mm-btn primary" disabled={busy}>Criar usuário</button></footer></form></div></div>}
  </section>
}
